language: python
python:
  - 2.7
install:
  - python bootstrap.py
  - bin/buildout -q
script:
  - bin/vvv setup.py
  - bin/vvv src/opensezame
  - bin/test
notifications:
  irc:
    - "irc.sioff.net#kiberpipa"
